extends:
  - airbnb-base
  - plugin:flowtype/recommended
  - plugin:jest/recommended
  - prettier

parser: '@babel/eslint-parser'

plugins:
  - flowtype
  - jest

globals:
  atom: true
  document: false

env:
  node: true
  jest: true

rules:
  no-mixed-operators: 0 # incompatible with prettier
  no-confusing-arrow: 0 # incompatible with prettier
  max-len: 0 # prefer prettier
  prefer-destructuring: 0 # not always preferable
