// flow-typed signature: 456558496d78348a88fc2765a1359bec
// flow-typed version: <<STUB>>/all-contributors-cli_v^6.7.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'all-contributors-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'all-contributors-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'all-contributors-cli/dist/api' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/cli' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/__tests__/add' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/__tests__/addWithDetails' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/__tests__/fixtures/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/__tests__/prompt' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/add' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/addWithDetails' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/prompt' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/__tests__/format-badge' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/__tests__/format-contribution-type' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/__tests__/format-contributor' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/__tests__/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/format-badge' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/format-contribution-type' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/format-contributor' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/__tests__/add-badge' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/__tests__/add-contributors-list' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/commit-conventions' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/file-exist' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/init-content' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/prompt' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/__tests__/github' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/__tests__/gitlab' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/__tests__/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/github' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/gitlab' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/__tests__/config-file' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/config-file' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/contribution-types' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/git' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'all-contributors-cli/dist/api.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/api'>;
}
declare module 'all-contributors-cli/dist/cli.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/cli'>;
}
declare module 'all-contributors-cli/dist/contributors/__tests__/add.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/__tests__/add'>;
}
declare module 'all-contributors-cli/dist/contributors/__tests__/addWithDetails.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/__tests__/addWithDetails'>;
}
declare module 'all-contributors-cli/dist/contributors/__tests__/fixtures/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/__tests__/fixtures/index'>;
}
declare module 'all-contributors-cli/dist/contributors/__tests__/prompt.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/__tests__/prompt'>;
}
declare module 'all-contributors-cli/dist/contributors/add.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/add'>;
}
declare module 'all-contributors-cli/dist/contributors/addWithDetails.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/addWithDetails'>;
}
declare module 'all-contributors-cli/dist/contributors/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/index'>;
}
declare module 'all-contributors-cli/dist/contributors/prompt.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/prompt'>;
}
declare module 'all-contributors-cli/dist/generate/__tests__/format-badge.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/__tests__/format-badge'>;
}
declare module 'all-contributors-cli/dist/generate/__tests__/format-contribution-type.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/__tests__/format-contribution-type'>;
}
declare module 'all-contributors-cli/dist/generate/__tests__/format-contributor.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/__tests__/format-contributor'>;
}
declare module 'all-contributors-cli/dist/generate/__tests__/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/__tests__/index'>;
}
declare module 'all-contributors-cli/dist/generate/format-badge.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/format-badge'>;
}
declare module 'all-contributors-cli/dist/generate/format-contribution-type.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/format-contribution-type'>;
}
declare module 'all-contributors-cli/dist/generate/format-contributor.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/format-contributor'>;
}
declare module 'all-contributors-cli/dist/generate/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/index'>;
}
declare module 'all-contributors-cli/dist/init/__tests__/add-badge.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/__tests__/add-badge'>;
}
declare module 'all-contributors-cli/dist/init/__tests__/add-contributors-list.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/__tests__/add-contributors-list'>;
}
declare module 'all-contributors-cli/dist/init/commit-conventions.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/commit-conventions'>;
}
declare module 'all-contributors-cli/dist/init/file-exist.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/file-exist'>;
}
declare module 'all-contributors-cli/dist/init/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/index'>;
}
declare module 'all-contributors-cli/dist/init/init-content.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/init-content'>;
}
declare module 'all-contributors-cli/dist/init/prompt.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/prompt'>;
}
declare module 'all-contributors-cli/dist/repo/__tests__/github.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/__tests__/github'>;
}
declare module 'all-contributors-cli/dist/repo/__tests__/gitlab.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/__tests__/gitlab'>;
}
declare module 'all-contributors-cli/dist/repo/__tests__/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/__tests__/index'>;
}
declare module 'all-contributors-cli/dist/repo/github.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/github'>;
}
declare module 'all-contributors-cli/dist/repo/gitlab.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/gitlab'>;
}
declare module 'all-contributors-cli/dist/repo/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/index'>;
}
declare module 'all-contributors-cli/dist/util/__tests__/config-file.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/__tests__/config-file'>;
}
declare module 'all-contributors-cli/dist/util/config-file.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/config-file'>;
}
declare module 'all-contributors-cli/dist/util/contribution-types.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/contribution-types'>;
}
declare module 'all-contributors-cli/dist/util/git.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/git'>;
}
declare module 'all-contributors-cli/dist/util/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/index'>;
}
declare module 'all-contributors-cli/dist/util/markdown.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/markdown'>;
}
