// flow-typed signature: 232f1d8eb0d6da9baa891fb43c8737f8
// flow-typed version: <<STUB>>/all-contributors-cli_v^6.20.0/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'all-contributors-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'all-contributors-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'all-contributors-cli/dist/api' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/cli' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/add' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/addWithDetails' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/prompt' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/format-badge' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/format-contribution-type' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/format-contributor' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/commit-conventions' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/file-exist' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/init-content' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/prompt' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/github' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/gitlab' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/config-file' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/contribution-types' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/git' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/markdown' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'all-contributors-cli/dist/api.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/api'>;
}
declare module 'all-contributors-cli/dist/cli.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/cli'>;
}
declare module 'all-contributors-cli/dist/contributors/add.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/add'>;
}
declare module 'all-contributors-cli/dist/contributors/addWithDetails.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/addWithDetails'>;
}
declare module 'all-contributors-cli/dist/contributors/index' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors'>;
}
declare module 'all-contributors-cli/dist/contributors/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors'>;
}
declare module 'all-contributors-cli/dist/contributors/prompt.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/prompt'>;
}
declare module 'all-contributors-cli/dist/generate/format-badge.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/format-badge'>;
}
declare module 'all-contributors-cli/dist/generate/format-contribution-type.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/format-contribution-type'>;
}
declare module 'all-contributors-cli/dist/generate/format-contributor.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/format-contributor'>;
}
declare module 'all-contributors-cli/dist/generate/index' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate'>;
}
declare module 'all-contributors-cli/dist/generate/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate'>;
}
declare module 'all-contributors-cli/dist/init/commit-conventions.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/commit-conventions'>;
}
declare module 'all-contributors-cli/dist/init/file-exist.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/file-exist'>;
}
declare module 'all-contributors-cli/dist/init/index' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init'>;
}
declare module 'all-contributors-cli/dist/init/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init'>;
}
declare module 'all-contributors-cli/dist/init/init-content.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/init-content'>;
}
declare module 'all-contributors-cli/dist/init/prompt.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/prompt'>;
}
declare module 'all-contributors-cli/dist/repo/github.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/github'>;
}
declare module 'all-contributors-cli/dist/repo/gitlab.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/gitlab'>;
}
declare module 'all-contributors-cli/dist/repo/index' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo'>;
}
declare module 'all-contributors-cli/dist/repo/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo'>;
}
declare module 'all-contributors-cli/dist/util/config-file.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/config-file'>;
}
declare module 'all-contributors-cli/dist/util/contribution-types.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/contribution-types'>;
}
declare module 'all-contributors-cli/dist/util/git.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/git'>;
}
declare module 'all-contributors-cli/dist/util/index' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util'>;
}
declare module 'all-contributors-cli/dist/util/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util'>;
}
declare module 'all-contributors-cli/dist/util/markdown.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/markdown'>;
}
declare module 'all-contributors-cli/dist/util/url.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/url'>;
}
