// flow-typed signature: 20cc54457f53623987d75923b94150e3
// flow-typed version: <<STUB>>/atom-package-deps_v^8.0.0/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-package-deps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-package-deps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-package-deps/lib/bin' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-package-deps/lib/bin.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/bin'>;
}
declare module 'atom-package-deps/lib/index' {
  declare module.exports: $Exports<'atom-package-deps/lib'>;
}
declare module 'atom-package-deps/lib/index.js' {
  declare module.exports: $Exports<'atom-package-deps/lib'>;
}
