// flow-typed signature: 2ffb85ac3a7852ca33f07fd64606c75f
// flow-typed version: <<STUB>>/atom-package-deps_v^4.6.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-package-deps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-package-deps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-package-deps/lib/helpers' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib/index' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib/types' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib/view' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-package-deps/lib/helpers.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/helpers'>;
}
declare module 'atom-package-deps/lib/index.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/index'>;
}
declare module 'atom-package-deps/lib/types.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/types'>;
}
declare module 'atom-package-deps/lib/view.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/view'>;
}
