// flow-typed signature: bb3f6d09915e00d0cd801482d774df9d
// flow-typed version: <<STUB>>/atom-text-buffer-range_v^1.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-text-buffer-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-text-buffer-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-text-buffer-range/range' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-text-buffer-range/range.js' {
  declare module.exports: $Exports<'atom-text-buffer-range/range'>;
}
