// flow-typed signature: c1c626ae953874606e9c5d5d5139e4e2
// flow-typed version: <<STUB>>/atom-text-buffer-point_v^1.0.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-text-buffer-point'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-text-buffer-point' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-text-buffer-point/point' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-text-buffer-point/point.js' {
  declare module.exports: $Exports<'atom-text-buffer-point/point'>;
}
