// flow-typed signature: 0c9afdb259b9bba8c6d59e369520c4b9
// flow-typed version: <<STUB>>/atom-package-deps_v^6.0.0/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-package-deps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-package-deps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-package-deps/lib/index-6660c169' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib/install-03586186' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib/prompt-afef23e0' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-package-deps/lib/index-6660c169.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/index-6660c169'>;
}
declare module 'atom-package-deps/lib/index' {
  declare module.exports: $Exports<'atom-package-deps/lib'>;
}
declare module 'atom-package-deps/lib/index.js' {
  declare module.exports: $Exports<'atom-package-deps/lib'>;
}
declare module 'atom-package-deps/lib/install-03586186.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/install-03586186'>;
}
declare module 'atom-package-deps/lib/prompt-afef23e0.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/prompt-afef23e0'>;
}
