// flow-typed signature: bacd06b5b02609c055d96cf2f5800dab
// flow-typed version: <<STUB>>/atom-linter_v^10.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-linter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-linter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-linter/lib/helpers' {
  declare module.exports: any;
}

declare module 'atom-linter/lib/index' {
  declare module.exports: any;
}

declare module 'atom-linter/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-linter/lib/helpers.js' {
  declare module.exports: $Exports<'atom-linter/lib/helpers'>;
}
declare module 'atom-linter/lib/index.js' {
  declare module.exports: $Exports<'atom-linter/lib/index'>;
}
declare module 'atom-linter/lib/types.js' {
  declare module.exports: $Exports<'atom-linter/lib/types'>;
}
