// flow-typed signature: ddc6985a1bab4886e5d013887c34b7e7
// flow-typed version: <<STUB>>/conventional-changelog-cli_v^2.1.1/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conventional-changelog-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'conventional-changelog-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'conventional-changelog-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'conventional-changelog-cli/cli.js' {
  declare module.exports: $Exports<'conventional-changelog-cli/cli'>;
}
