// flow-typed signature: 5fbc3b0f2c4199f8a1e20ea700c027ae
// flow-typed version: <<STUB>>/editorconfig_v^0.14.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'editorconfig'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'editorconfig' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'editorconfig/editorconfig' {
  declare module.exports: any;
}

declare module 'editorconfig/lib/fnmatch' {
  declare module.exports: any;
}

declare module 'editorconfig/lib/ini' {
  declare module.exports: any;
}

// Filename aliases
declare module 'editorconfig/editorconfig.js' {
  declare module.exports: $Exports<'editorconfig/editorconfig'>;
}
declare module 'editorconfig/lib/fnmatch.js' {
  declare module.exports: $Exports<'editorconfig/lib/fnmatch'>;
}
declare module 'editorconfig/lib/ini.js' {
  declare module.exports: $Exports<'editorconfig/lib/ini'>;
}
