// flow-typed signature: 045354dc3abbed73e00de8197cc5f5c9
// flow-typed version: <<STUB>>/editorconfig_v^0.13.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'editorconfig'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'editorconfig' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'editorconfig/editorconfig' {
  declare module.exports: any;
}

declare module 'editorconfig/lib/fnmatch' {
  declare module.exports: any;
}

declare module 'editorconfig/lib/ini' {
  declare module.exports: any;
}

declare module 'editorconfig/lib/version' {
  declare module.exports: any;
}

declare module 'editorconfig/test/app' {
  declare module.exports: any;
}

declare module 'editorconfig/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'editorconfig/editorconfig.js' {
  declare module.exports: $Exports<'editorconfig/editorconfig'>;
}
declare module 'editorconfig/lib/fnmatch.js' {
  declare module.exports: $Exports<'editorconfig/lib/fnmatch'>;
}
declare module 'editorconfig/lib/ini.js' {
  declare module.exports: $Exports<'editorconfig/lib/ini'>;
}
declare module 'editorconfig/lib/version.js' {
  declare module.exports: $Exports<'editorconfig/lib/version'>;
}
declare module 'editorconfig/test/app.js' {
  declare module.exports: $Exports<'editorconfig/test/app'>;
}
declare module 'editorconfig/test/index.js' {
  declare module.exports: $Exports<'editorconfig/test/index'>;
}
