// flow-typed signature: efef5701ac0ec3e50c217b7984c930bc
// flow-typed version: <<STUB>>/editorconfig-to-prettier_v^0.0.6/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'editorconfig-to-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'editorconfig-to-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'editorconfig-to-prettier/index' {
  declare module.exports: $Exports<'editorconfig-to-prettier'>;
}
declare module 'editorconfig-to-prettier/index.js' {
  declare module.exports: $Exports<'editorconfig-to-prettier'>;
}
