// flow-typed signature: 809a740bdf86662e7d93c765be8fef03
// flow-typed version: <<STUB>>/ignore_v^3.3.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignore/ignore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignore/ignore.js' {
  declare module.exports: $Exports<'ignore/ignore'>;
}
