// flow-typed signature: 7d957770bda3e554e204d03c2fd94edd
// flow-typed version: <<STUB>>/ignore_v^5.0.4/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignore/legacy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignore/index' {
  declare module.exports: $Exports<'ignore'>;
}
declare module 'ignore/index.js' {
  declare module.exports: $Exports<'ignore'>;
}
declare module 'ignore/legacy.js' {
  declare module.exports: $Exports<'ignore/legacy'>;
}
