// flow-typed signature: 72edba53e3dcfcd9c879d67f7b044bc8
// flow-typed version: <<STUB>>/nps_v^5.3.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nps/dist/__mocks__/console' {
  declare module.exports: any;
}

declare module 'nps/dist/__mocks__/find-up' {
  declare module.exports: any;
}

declare module 'nps/dist/__mocks__/get-logger' {
  declare module.exports: any;
}

declare module 'nps/dist/__mocks__/readline-sync' {
  declare module.exports: any;
}

declare module 'nps/dist/bin-utils/autocomplete-get-scripts' {
  declare module.exports: any;
}

declare module 'nps/dist/bin-utils/index' {
  declare module.exports: any;
}

declare module 'nps/dist/bin-utils/initialize/index' {
  declare module.exports: any;
}

declare module 'nps/dist/bin-utils/parser' {
  declare module.exports: any;
}

declare module 'nps/dist/bin/nps' {
  declare module.exports: any;
}

declare module 'nps/dist/get-logger' {
  declare module.exports: any;
}

declare module 'nps/dist/get-script-to-run' {
  declare module.exports: any;
}

declare module 'nps/dist/get-scripts-from-config' {
  declare module.exports: any;
}

declare module 'nps/dist/index' {
  declare module.exports: any;
}

declare module 'nps/dist/kebab-and-camel-casify' {
  declare module.exports: any;
}

declare module 'nps/dist/resolve-script-object-to-string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nps/dist/__mocks__/console.js' {
  declare module.exports: $Exports<'nps/dist/__mocks__/console'>;
}
declare module 'nps/dist/__mocks__/find-up.js' {
  declare module.exports: $Exports<'nps/dist/__mocks__/find-up'>;
}
declare module 'nps/dist/__mocks__/get-logger.js' {
  declare module.exports: $Exports<'nps/dist/__mocks__/get-logger'>;
}
declare module 'nps/dist/__mocks__/readline-sync.js' {
  declare module.exports: $Exports<'nps/dist/__mocks__/readline-sync'>;
}
declare module 'nps/dist/bin-utils/autocomplete-get-scripts.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/autocomplete-get-scripts'>;
}
declare module 'nps/dist/bin-utils/index.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/index'>;
}
declare module 'nps/dist/bin-utils/initialize/index.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/initialize/index'>;
}
declare module 'nps/dist/bin-utils/parser.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/parser'>;
}
declare module 'nps/dist/bin/nps.js' {
  declare module.exports: $Exports<'nps/dist/bin/nps'>;
}
declare module 'nps/dist/get-logger.js' {
  declare module.exports: $Exports<'nps/dist/get-logger'>;
}
declare module 'nps/dist/get-script-to-run.js' {
  declare module.exports: $Exports<'nps/dist/get-script-to-run'>;
}
declare module 'nps/dist/get-scripts-from-config.js' {
  declare module.exports: $Exports<'nps/dist/get-scripts-from-config'>;
}
declare module 'nps/dist/index.js' {
  declare module.exports: $Exports<'nps/dist/index'>;
}
declare module 'nps/dist/kebab-and-camel-casify.js' {
  declare module.exports: $Exports<'nps/dist/kebab-and-camel-casify'>;
}
declare module 'nps/dist/resolve-script-object-to-string.js' {
  declare module.exports: $Exports<'nps/dist/resolve-script-object-to-string'>;
}
