// flow-typed signature: 89bdd71901687ff19d6613a199c130fe
// flow-typed version: <<STUB>>/nps_v^5.7.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nps/dist/bin-utils/autocomplete-get-scripts' {
  declare module.exports: any;
}

declare module 'nps/dist/bin-utils/get-script-by-prefix' {
  declare module.exports: any;
}

declare module 'nps/dist/bin-utils/index' {
  declare module.exports: any;
}

declare module 'nps/dist/bin-utils/initialize/index' {
  declare module.exports: any;
}

declare module 'nps/dist/bin-utils/initialize/stringify-object' {
  declare module.exports: any;
}

declare module 'nps/dist/bin-utils/parser' {
  declare module.exports: any;
}

declare module 'nps/dist/bin/nps' {
  declare module.exports: any;
}

declare module 'nps/dist/get-logger' {
  declare module.exports: any;
}

declare module 'nps/dist/get-script-to-run' {
  declare module.exports: any;
}

declare module 'nps/dist/get-scripts-from-config' {
  declare module.exports: any;
}

declare module 'nps/dist/index' {
  declare module.exports: any;
}

declare module 'nps/dist/kebab-and-camel-casify' {
  declare module.exports: any;
}

declare module 'nps/dist/resolve-script-object-to-string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nps/dist/bin-utils/autocomplete-get-scripts.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/autocomplete-get-scripts'>;
}
declare module 'nps/dist/bin-utils/get-script-by-prefix.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/get-script-by-prefix'>;
}
declare module 'nps/dist/bin-utils/index.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/index'>;
}
declare module 'nps/dist/bin-utils/initialize/index.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/initialize/index'>;
}
declare module 'nps/dist/bin-utils/initialize/stringify-object.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/initialize/stringify-object'>;
}
declare module 'nps/dist/bin-utils/parser.js' {
  declare module.exports: $Exports<'nps/dist/bin-utils/parser'>;
}
declare module 'nps/dist/bin/nps.js' {
  declare module.exports: $Exports<'nps/dist/bin/nps'>;
}
declare module 'nps/dist/get-logger.js' {
  declare module.exports: $Exports<'nps/dist/get-logger'>;
}
declare module 'nps/dist/get-script-to-run.js' {
  declare module.exports: $Exports<'nps/dist/get-script-to-run'>;
}
declare module 'nps/dist/get-scripts-from-config.js' {
  declare module.exports: $Exports<'nps/dist/get-scripts-from-config'>;
}
declare module 'nps/dist/index.js' {
  declare module.exports: $Exports<'nps/dist/index'>;
}
declare module 'nps/dist/kebab-and-camel-casify.js' {
  declare module.exports: $Exports<'nps/dist/kebab-and-camel-casify'>;
}
declare module 'nps/dist/resolve-script-object-to-string.js' {
  declare module.exports: $Exports<'nps/dist/resolve-script-object-to-string'>;
}
