// flow-typed signature: 21038fd4e83d54589c31902b4d200762
// flow-typed version: <<STUB>>/opt-cli_v^1.6.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opt-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opt-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opt-cli/bin/index' {
  declare module.exports: any;
}

declare module 'opt-cli/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opt-cli/bin/index.js' {
  declare module.exports: $Exports<'opt-cli/bin/index'>;
}
declare module 'opt-cli/lib/index.js' {
  declare module.exports: $Exports<'opt-cli/lib/index'>;
}
