// flow-typed signature: ec5ca338536ae1e8c533ad3c0ead1200
// flow-typed version: <<STUB>>/prettier-eslint_v^14.0.2/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-eslint/dist' {
  declare module.exports: any;
}

declare module 'prettier-eslint/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-eslint/dist/index' {
  declare module.exports: $Exports<'prettier-eslint/dist'>;
}
declare module 'prettier-eslint/dist/index.js' {
  declare module.exports: $Exports<'prettier-eslint/dist'>;
}
declare module 'prettier-eslint/dist/utils.js' {
  declare module.exports: $Exports<'prettier-eslint/dist/utils'>;
}
