// flow-typed signature: 24d1839b6e9ab63c45a16a9d8fbd4d9d
// flow-typed version: <<STUB>>/prettier-stylelint_v^0.4.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-stylelint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-stylelint/cli' {
  declare module.exports: any;
}

declare module 'prettier-stylelint/config' {
  declare module.exports: any;
}

declare module 'prettier-stylelint/src/cli' {
  declare module.exports: any;
}

declare module 'prettier-stylelint/src/index' {
  declare module.exports: any;
}

declare module 'prettier-stylelint/src/utils' {
  declare module.exports: any;
}

declare module 'prettier-stylelint/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-stylelint/cli.js' {
  declare module.exports: $Exports<'prettier-stylelint/cli'>;
}
declare module 'prettier-stylelint/config.js' {
  declare module.exports: $Exports<'prettier-stylelint/config'>;
}
declare module 'prettier-stylelint/index' {
  declare module.exports: $Exports<'prettier-stylelint'>;
}
declare module 'prettier-stylelint/index.js' {
  declare module.exports: $Exports<'prettier-stylelint'>;
}
declare module 'prettier-stylelint/src/cli.js' {
  declare module.exports: $Exports<'prettier-stylelint/src/cli'>;
}
declare module 'prettier-stylelint/src/index.js' {
  declare module.exports: $Exports<'prettier-stylelint/src/index'>;
}
declare module 'prettier-stylelint/src/utils.js' {
  declare module.exports: $Exports<'prettier-stylelint/src/utils'>;
}
declare module 'prettier-stylelint/test.js' {
  declare module.exports: $Exports<'prettier-stylelint/test'>;
}
