// flow-typed signature: 9fccae786329f3def80f2cf17d485f01
// flow-typed version: <<STUB>>/prettier-eslint-cli_v^3.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-eslint-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-eslint-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-eslint-cli/dist/format-files' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/index' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/messages' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/no-main' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-eslint-cli/dist/format-files.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/format-files'>;
}
declare module 'prettier-eslint-cli/dist/index.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/index'>;
}
declare module 'prettier-eslint-cli/dist/messages.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/messages'>;
}
declare module 'prettier-eslint-cli/dist/no-main.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/no-main'>;
}
declare module 'prettier-eslint-cli/dist/parser.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/parser'>;
}
