// flow-typed signature: a5a3c5d4a34aff1a8792240832bee67a
// flow-typed version: <<STUB>>/read-pkg_v^2.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'read-pkg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'read-pkg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'read-pkg/index' {
  declare module.exports: $Exports<'read-pkg'>;
}
declare module 'read-pkg/index.js' {
  declare module.exports: $Exports<'read-pkg'>;
}
