// flow-typed signature: c5d4c61f5a2e9cb01369a03072d97d0c
// flow-typed version: <<STUB>>/read-pkg-up_v^3.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'read-pkg-up'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'read-pkg-up' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'read-pkg-up/index' {
  declare module.exports: $Exports<'read-pkg-up'>;
}
declare module 'read-pkg-up/index.js' {
  declare module.exports: $Exports<'read-pkg-up'>;
}
