// flow-typed signature: 3a2b5de98ecfeaca60e9de1872d73515
// flow-typed version: <<STUB>>/yarn-global-modules_v^1.0.1/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarn-global-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarn-global-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'yarn-global-modules/index' {
  declare module.exports: $Exports<'yarn-global-modules'>;
}
declare module 'yarn-global-modules/index.js' {
  declare module.exports: $Exports<'yarn-global-modules'>;
}
