// flow-typed signature: 6ca4a0d73eda7606618ec6a735024dcd
// flow-typed version: <<STUB>>/@babel/plugin-transform-runtime_v^7.15.0/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-runtime/lib/get-runtime-path/browser' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-runtime/lib/get-runtime-path' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-runtime/lib/helpers' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-runtime/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-runtime/lib/get-runtime-path/browser.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib/get-runtime-path/browser'>;
}
declare module '@babel/plugin-transform-runtime/lib/get-runtime-path/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib/get-runtime-path'>;
}
declare module '@babel/plugin-transform-runtime/lib/get-runtime-path/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib/get-runtime-path'>;
}
declare module '@babel/plugin-transform-runtime/lib/helpers.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib/helpers'>;
}
declare module '@babel/plugin-transform-runtime/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib'>;
}
declare module '@babel/plugin-transform-runtime/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-runtime/lib'>;
}
