// flow-typed signature: 4e156cc8d2f0ed15acc1c94bcd6151d9
// flow-typed version: <<STUB>>/@lewisl9029/prettier-eslint_v^9.0.1/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lewisl9029/prettier-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lewisl9029/prettier-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lewisl9029/prettier-eslint/dist' {
  declare module.exports: any;
}

declare module '@lewisl9029/prettier-eslint/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lewisl9029/prettier-eslint/dist/index' {
  declare module.exports: $Exports<'@lewisl9029/prettier-eslint/dist'>;
}
declare module '@lewisl9029/prettier-eslint/dist/index.js' {
  declare module.exports: $Exports<'@lewisl9029/prettier-eslint/dist'>;
}
declare module '@lewisl9029/prettier-eslint/dist/utils.js' {
  declare module.exports: $Exports<'@lewisl9029/prettier-eslint/dist/utils'>;
}
